### ISSUE TITLE
segbot_simulation_apps: target 'door_handler' should be more unique

### ISSUE THREAD

**Issue by jack-oquin** [utexas-bwi/segbot_simulator#19]
This issue was raised by catkin_lint, because catkin library names are global to entire ROS distribution. 

Including the entire package name, as catkin_lint suggests, is probably overkill. But, some project-oriented prefix seems reasonable. I suggest ``bwi_door_handler``, unless this interface is really unique to the segbot, in which case ``segbot_simulation_door_handler`` might be appropriate.

**Comment by piyushk** [comment]
I'm closing this issue. I don't plan on fixing target name unique errors any more.

**Comment by jack-oquin** [comment]
It probably wouldn't hurt to add a ``bwi_`` prefix to most of our target names. That way we never have to worry about catkin_make blowing up when building a large workspace containing lots of other packages.
